### ISSUE TITLE
Crash upon playing version 1.20.1

### ISSUE THREAD

**Issue by Gensokian** [george8188625/Create-Diesel-Generators#27]
# Basic descryption:
Upon loading Minecraft forge automatically goes to the "ERROR DURING MODLOADING" page and shows the following screen:
![image](https://github.com/george8188625/Create-Diesel-Generators/assets/9213561/37f7ca5f-13ae-4612-810b-510df3198e36)

**NOTE**
When launching with create revision d this doesn't happen.

# Testcases:
Multiple mods
Only Dieselgenerators + Create

# Useful infos

* Forge Version: 47.2.1
* Mod Version: createdieselgenerators-1.20.1-1.1d
* Create version: create-1.20.1-0.5.1.e

# Trace
```log
[13:30:08] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: createdieselgenerators, class com.jesz.createdieselgenerators.CreateDieselGenerators
java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)'
	at com.jesz.createdieselgenerators.blocks.BlockRegistry.<clinit>(BlockRegistry.java:19) ~[createdieselgenerators-1.20.1-1.1d.jar%23275!/:1.20.1-1.1d]
	at com.jesz.createdieselgenerators.CreateDieselGenerators.<init>(CreateDieselGenerators.java:38) ~[createdieselgenerators-1.20.1-1.1d.jar%23275!/:1.20.1-1.1d]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.1.jar%23348!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.1.jar%23347!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by george8188625** [comment]
Downgrade create to 0.5.1d

**Comment by george8188625** [comment]
Create 0.5.1e is gonna be supported in the next version of the mod

**Comment by Gensokian** [comment]
Thanks for the prompt response!
