### ISSUE TITLE
[1.19.2] Pondering crashes client

### ISSUE THREAD

**Issue by Nycto97** [george8188625/Create-Diesel-Generators#58]
I was looking at a ponder scene from item `Diesel Engine` and my client crashed.

Forge 1.19.2
createdieselgenerators-1.19.2-1.2f

`java.lang.NullPointerException: Cannot invoke "com.jesz.createdieselgenerators.other.CDGFuelType.getGeneratedNormal()" because the return value of "com.jesz.createdieselgenerators.other.FuelTypeManager.getType(net.minecraft.world.level.material.Fluid)" is null`

[crash-2023-12-27_13.38.05-client.txt](https://github.com/george8188625/Create-Diesel-Generators/files/13778622/crash-2023-12-27_13.38.05-client.txt)

**Comment by george8188625** [comment]
Weird, I'm gonna take a look into that

**Comment by Nycto97** [comment]
I have another crash while pondering `Disenchanter` from `Create: Enchantment Industry`.

I'm not sure if it is related to this mod, it looks like a `CIT Resewn` issue.

[crash-2023-12-29_16.56.34-client.txt](https://github.com/george8188625/Create-Diesel-Generators/files/13794741/crash-2023-12-29_16.56.34-client.txt)

**Comment by TheBlckbird** [comment]
I have the same problem. The game crashes when while pondering any of the diesel engines. It’s very annoying. Is there any workaround/ fix for it?

I’m using the newest version of the mod in 1.20.1 with Neoforge

**Comment by sherlockzym** [comment]
same problem，When I play in the customer service side, when I think about the diesel engine, I report an error to exit the client side, and I can play a short paragraph, which seems to be an error when displaying the liquid, the server does not report an error, and the client reports an error message

java.lang.NullPointerException: Cannot invoke "com.jesz.createdieselgenerators.other.CDGFuelType.getGeneratedNormal()" because the return value of "com.jesz.createdieselgenerators.other.FuelTypeManager.getType(net.minecraft.world.level.material.Fluid)" is null
	at com.jesz.createdieselgenerators.ponder.DieselEngineScenes.lambda$small$5(DieselEngineScenes.java:87) ~[createdieselgenerators-1.19.2-1.2f.jar%23534!/:1.19.2-1.2f] {re:classloading}
	at com.simibubi.create.foundation.ponder.SceneBuilder$WorldInstructions.lambda$modifyKineticSpeed$30(SceneBuilder.java:809) ~[create-1.19.2-0.5.1.f.jar%23529!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.ponder.SceneBuilder$WorldInstructions.lambda$modifyBlockEntityNBT$34(SceneBuilder.java:841) ~[create-1.19.2-0.5.1.f.jar%23529!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.ponder.instruction.BlockEntityDataInstruction.lambda$runModification$0(BlockEntityDataInstruction.java:37) ~[create-1.19.2-0.5.1.f.jar%23529!/:0.5.1.f] {re:classloading}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at com.simibubi.create.foundation.ponder.Selection$Simple.forEach(Selection.java:131) ~[create-1.19.2-0.5.1.f.jar%23529!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.ponder.instruction.BlockEntityDataInstruction.runModification(BlockEntityDataInstruction.java:30) ~[create-1.19.2-0.5.1.f.jar%23529!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.ponder.instruction.WorldModifyInstruction.tick(WorldModifyInstruction.java:22) ~[create-1.19.2-0.5.1.f.jar%23529!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.ponder.PonderScene.tick(PonderScene.java:291) ~[create-1.19.2-0.5.1.f.jar%23529!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.ponder.ui.PonderUI.m_86600_(PonderUI.java:304) ~[create-1.19.2-0.5.1.f.jar%23529!/:0.5.1.f] {re:classloading}
	at net.minecraft.client.Minecraft.m_231445_(Minecraft.java:1758) ~[client-1.19.2-20220805.130853-srg.jar%23768!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23768!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:kiwi.mixins.json:client.ScreenMixin,pl:mixin:APP:byg.mixins.json:access.client.ScreenAccess,pl:mixin:APP:aether.mixins.json:client.accessor.ScreenAccessor,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:equipmentcompare.mixins.json:ScreenMixin,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:betterstats.client.mixin.json:MixinScreen,pl:mixin:APP:iceberg.mixins.json:ScreenMixin,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1757) ~[client-1.19.2-20220805.130853-srg.jar%23768!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078) ~[client-1.19.2-20220805.130853-srg.jar%23768!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23768!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23768!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23768!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

**Comment by sherlockzym** [comment]
[Uploading crash-2024-02-03_13.05.36-client.txt…]()
