### ISSUE TITLE
What is problem? Critical injection failure on client startup

### ISSUE THREAD

**Issue by Leelin1** [george8188625/Create-Diesel-Generators#70]
[251월2024 11:39:25.454] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "BetterF3-7.0.2-Forge-1.20.1.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.454] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "BiomesOPlenty-1.20.1-18.0.0.598.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.455] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "cc-tweaked-1.20.1-forge-1.109.3.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.455] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "cloth-config-11.1.118-forge.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.455] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "create-1.20.1-0.5.1.f.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.455] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "createaddition-1.20.1-1.1.1.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.456] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "createdieselgenerators-1.20.1-1.2f.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.456] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "createutilities-0.1.4+1.20.1.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.456] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "jei-1.20.1-forge-15.2.0.27.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.456] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "Mekanism-1.20.1-10.4.5.19.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.456] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "MekanismAdditions-1.20.1-10.4.5.19.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.457] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "MekanismGenerators-1.20.1-10.4.5.19.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.457] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "MekanismTools-1.20.1-10.4.5.19.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.457] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "memoryleakfix-forge-1.17+-1.1.5.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.458] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "sound-physics-remastered-forge-1.20.1-1.3.1.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.458] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "TerraBlender-forge-1.20.1-3.0.1.2.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.458] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "Xaeros_Minimap_23.9.3_Forge_1.20.jar" of type MOD with provider {mods folder locator at C:\Users\Hanlim\AppData\Roaming\.minecraft\mods}
[251월2024 11:39:25.687] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Hanlim\AppData\Roaming\.minecraft\libraries\net\neoforged\fancymodloader\core\47.1.47\core-47.1.47.jar is missing mods.toml file
[251월2024 11:39:25.693] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Hanlim\AppData\Roaming\.minecraft\libraries\net\neoforged\fancymodloader\language-java\47.1.47\language-java-47.1.47.jar is missing mods.toml file
[251월2024 11:39:25.699] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Hanlim\AppData\Roaming\.minecraft\libraries\net\neoforged\fancymodloader\language-lowcode\47.1.47\language-lowcode-47.1.47.jar is missing mods.toml file
[251월2024 11:39:25.704] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Hanlim\AppData\Roaming\.minecraft\libraries\net\neoforged\fancymodloader\language-minecraft\47.1.47\language-minecraft-47.1.47.jar is missing mods.toml file
[251월2024 11:39:25.717] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "core-47.1.47.jar" of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@37fdfb05
[251월2024 11:39:25.717] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "language-java-47.1.47.jar" of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@37fdfb05
[251월2024 11:39:25.717] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "language-lowcode-47.1.47.jar" of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@37fdfb05
[251월2024 11:39:25.719] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "language-minecraft-47.1.47.jar" of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@37fdfb05
[251월2024 11:39:25.719] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "client-1.20.1-20230612.114412-srg.jar" of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@37fdfb05
[251월2024 11:39:25.719] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "forge-1.20.1-47.1.88-universal.jar" of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@37fdfb05
[251월2024 11:39:25.728] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "events-47.1.47.jar" of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.BuiltinGameLibraryLocator@7c455e96
[251월2024 11:39:25.984] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 7 dependencies adding them to mods collection
[251월2024 11:39:25.985] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "cobalt-0.8.2.jar" of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@522ba524
[251월2024 11:39:25.985] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "jzlib-1.1.3.jar" of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@522ba524
[251월2024 11:39:25.985] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "flywheel-forge-1.20.1-0.6.10-7.jar" of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@522ba524
[251월2024 11:39:25.986] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "netty-codec-socks-4.1.82.Final.jar" of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@522ba524
[251월2024 11:39:25.986] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "netty-handler-proxy-4.1.82.Final.jar" of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@522ba524
[251월2024 11:39:25.986] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "Registrate-MC1.20-1.3.3.jar" of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@522ba524
[251월2024 11:39:25.986] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "netty-codec-http-4.1.82.Final.jar" of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@522ba524
[251월2024 11:39:28.374] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[251월2024 11:39:28.624] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.sonicether.soundphysics.MixinConnector]
[251월2024 11:39:28.627] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1-forge-47.1.88, --gameDir, C:\Users\Hanlim\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Hanlim\AppData\Roaming\.minecraft\assets, --uuid, 43d423f9d0de4c80a8ab4354de978bb2, --username, Bineul_Dayo, --assetIndex, 5, --accessToken, ????????, --clientId, MzAyODllYzItZjMwOC00YmIyLWEwMjItYjg5YmI0OTQzYjE0, --xuid, 2535464370051867, --userType, msa, --versionType, release, --quickPlayPath, C:\Users\Hanlim\AppData\Roaming\.minecraft\quickPlay\java\1706150360603.json]
[251월2024 11:39:30.407] [main/INFO] [memoryleakfix/]: [MemoryLeakFix] Will be applying 3 memory leak fixes!
[251월2024 11:39:30.407] [main/INFO] [memoryleakfix/]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, biomeTemperatureLeak, hugeScreenshotLeak]
[251월2024 11:39:30.657] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via ca.fxco.memoryleakfix.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[251월2024 11:39:33.152] [pool-4-thread-1/FATAL] [mixin/]: Mixin apply failed createdieselgenerators.mixins.json:EntityMixin -> net.minecraft.world.entity.Entity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on tick could not find any targets matching 'tick()V' in net.minecraft.world.entity.Entity. Using refmap mixin.refmap.json [PREINJECT Applicator Phase -> createdieselgenerators.mixins.json:EntityMixin -> Prepare Injections ->  -> handler$zdp000$tick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on tick could not find any targets matching 'tick()V' in net.minecraft.world.entity.Entity. Using refmap mixin.refmap.json [PREINJECT Applicator Phase -> createdieselgenerators.mixins.json:EntityMixin -> Prepare Injections ->  -> handler$zdp000$tick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraftforge.registries.GameData.init(GameData.java:103) ~[forge-1.20.1-47.1.88-universal.jar%23195!/:?]
	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:88) ~[forge-1.20.1-47.1.88-universal.jar%23195!/:?]
	at net.minecraft.core.registries.BuiltInRegistries.forge(BuiltInRegistries.java:429) ~[client-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at net.minecraft.core.registries.BuiltInRegistries.forge(BuiltInRegistries.java:409) ~[client-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at net.minecraft.core.registries.BuiltInRegistries.<clinit>(BuiltInRegistries.java:121) ~[client-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[client-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by george8188625** [comment]
It's gonna get fixed in 1.2g, for now you can download the fix here https://cdn.discordapp.com/attachments/1122833659175632957/1199068661051302039/createdieselgenerators-1.20.1-1.2f.jar?ex=65c132b6&is=65aebdb6&hm=1044a72ec520ad9cb013b8b7925a802afbe084d174f2b546c0eacc7227878f93&
