### ISSUE TITLE
Incompatible with Create Fabric 0.5.1.f

### ISSUE THREAD

**Issue by dhouck** [george8188625/Create-Diesel-Generators#87]
You probably know this but itʼs worth having a tracking issue for.  The latest version of Create, 0.5.1.f, has changed various things and most add-on mods including this one are not compatible.

**Comment by hatkidchan** [comment]
Bumping this, that's one of the mods that stops me from updating to the latest Create

**Comment by hatkidchan** [comment]
just so we're on the same page, you're getting that crash log?
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createdieselgenerators'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.7-launcher.1.0.0.jar:1.0.0]
        Suppressed: java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraft.class_5321)'
                at com.robocraft999.creategoggles.fabric.CreateGogglesFabric.onInitialize(CreateGogglesFabric.java:13) ~[creategoggles-1.20.1-0.5.5.f-%5BFABRIC%5D.jar:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
                at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
                at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.7-launcher.1.0.0.jar:1.0.0]
Caused by: java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraft.class_5321)'
        at com.jesz.createdieselgenerators.blocks.BlockRegistry.<clinit>(BlockRegistry.java:19) ~[creatediselgenerators-2.1.3.jar:?]
        at com.jesz.createdieselgenerators.CreateDieselGenerators.onInitialize(CreateDieselGenerators.java:29) ~[creatediselgenerators-2.1.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
        ... 7 more
```

with
 - `creatediselgenerators-2.1.3.jar`
 - `create-fabric-0.5.1-f-build.1335+mc1.20.1.jar`
 - `fabric-server-mc.1.20.1-loader.0.15.7-launcher.1.0.0.jar`

**Comment by hatkidchan** [comment]
actually nvm creategoggles is also mentioned here and it's not updated to the latest create either
still crashes without it tho, just different traceback

<details>

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createdieselgenerators'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.7-launcher.1.0.0.jar:1.0.0]
Caused by: java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraft.class_5321)'
        at com.jesz.createdieselgenerators.blocks.BlockRegistry.<clinit>(BlockRegistry.java:19) ~[creatediselgenerators-2.1.3.jar:?]
        at com.jesz.createdieselgenerators.CreateDieselGenerators.onInitialize(CreateDieselGenerators.java:29) ~[creatediselgenerators-2.1.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
        ... 7 more

```
</details>

**Comment by hatkidchan** [comment]
would [that](https://github.com/Robocraft999/CreateGoggles/pull/35) patch be applicable here as well? I could try checking it tomorrow myself, but I doubt I'd go far..

**Comment by dadadadaan** [comment]
bumping this, since latest Create patch after F didn't do anything to fix it either.
