### ISSUE TITLE
[Crash] Minecart-Contraption assembly fails on 1.20.1-1.2h (Fabric)

### ISSUE THREAD

**Issue by joernott** [george8188625/Create-Diesel-Generators#91]
We're currently updating our modpack to 1.20.1 and added Create Diesel Generators 1.2h in alpha3.
One of our testers tried to assemble a minecart contraption in alpha3 and it crashed the game. Loading the saved game fails as it crashes every time. Loading the same saved game in alpha1 (without the diesel generators) works.

Minecraft version: 1.20.1
Create version: create-fabric-0.5.1-f-build.1335+mc1.20.1.jar
Create Diesel generators version: creatediselgenerators-1.2.2h.jar

I've attached the full log to see the full java stack trace, module list etc: [2024-04-02_minecraft-log-gambal.zip](https://github.com/george8188625/Create-Diesel-Generators/files/14838443/2024-04-02_minecraft-log-gambal.zip)

Crash report:
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-04-02 00:17:03
Description: Ticking block entity

java.lang.RuntimeException: Mixin transformation of com.simibubi.create.content.contraptions.MountedFluidStorage failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.simibubi.create.content.contraptions.MountedStorageManager.addBlock(MountedStorageManager.java:88)
	at com.simibubi.create.content.contraptions.Contraption.addBlock(Contraption.java:649)
	at com.simibubi.create.content.contraptions.Contraption.moveBlock(Contraption.java:431)
	at com.simibubi.create.content.contraptions.Contraption.searchMovedStructure(Contraption.java:243)
	at com.simibubi.create.content.contraptions.mounted.MountedContraption.assemble(MountedContraption.java:67)
	at com.simibubi.create.content.contraptions.mounted.CartAssemblerBlockEntity.assemble(CartAssemblerBlockEntity.java:130)
	at com.simibubi.create.content.contraptions.mounted.CartAssemblerBlockEntity.tryAssemble(CartAssemblerBlockEntity.java:84)
	at com.simibubi.create.content.contraptions.mounted.CartAssemblerBlockEntity.tick(CartAssemblerBlockEntity.java:65)
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.redirect$bih000$carpet$checkProcessBEs(class_2818.java:790)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.handler$bie000$carpet$modifiedRunLoop(MinecraftServer.java:14942)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 25 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [createdieselgenerators.mixins.json:MountedFluidStorageMixin from mod createdieselgenerators] from phase [DEFAULT] in config [createdieselgenerators.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 28 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on canUseAsStorage could not find any targets matching 'canUseAsStorage(Lnet/minecraft/world/level/block/entity/BlockEntity;)Z' in com.simibubi.create.content.contraptions.MountedFluidStorage. No refMap loaded. [PREINJECT Applicator Phase -> createdieselgenerators.mixins.json:MountedFluidStorageMixin from mod createdieselgenerators -> Prepare Injections ->  -> handler$hel000$createdieselgenerators$canUseAsStorage(Lnet/minecraft/class_2586;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor54.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 28 more

```

**Comment by george8188625** [comment]
The fabric version isn't finished and is very buggy. for now you can:
a) downgrade
b) wait for the finished version

**Comment by joernott** [comment]
Solution b it is then.
Thanks for the quick feedback and your great work. It is really fun to have all those mods in the Create environment.

**Comment by joernott** [comment]
I just tested 1.23h and it looks like assembling a minecart contraption works now.
