### ISSUE TITLE
ConcurrentModificationException: null upon large diesel engine connecting with an axle.

### ISSUE THREAD

**Issue by ABSOLUTEMAX123** [george8188625/Create-Diesel-Generators#98]
[19:58:09] [Render thread/ERROR]: Unreported exception thrown!
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
	at java.util.AbstractCollection.toArray(AbstractCollection.java:202) ~[?:?]
	at com.google.common.collect.Iterables.toArray(Iterables.java:300) ~[guava-31.1-jre.jar%23109!/:?]
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:701) ~[guava-31.1-jre.jar%23109!/:?]
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:686) ~[guava-31.1-jre.jar%23109!/:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.<init>(RenderChunk.java:32) ~[client-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.client.renderer.chunk.RenderRegionCache$ChunkInfo.m_200481_(RenderRegionCache.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.client.renderer.chunk.RenderRegionCache.m_200465_(RenderRegionCache.java:60) ~[client-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk.m_200437_(ChunkRenderDispatcher.java:452) ~[client-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk.m_200434_(ChunkRenderDispatcher.java:463) ~[client-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_194370_(LevelRenderer.java:2107) ~[client-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1164) ~[client-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstra
plauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
pack i was using is here: 
[M3C.zip](https://github.com/george8188625/Create-Diesel-Generators/files/15315377/M3C.zip)

**Comment by ABSOLUTEMAX123** [comment]
upon further experimentation, its a one-time crash, only upon first occurence, and does not occur after accessing the same world after crash
